[2024-01-16 15:53:23,894] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_transfer_gdrive_to_postgresql.check_file_if_exists manual__2024-01-16T15:53:22.144392+00:00 [queued]>
[2024-01-16 15:53:23,900] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_transfer_gdrive_to_postgresql.check_file_if_exists manual__2024-01-16T15:53:22.144392+00:00 [queued]>
[2024-01-16 15:53:23,900] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-01-16 15:53:23,901] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2024-01-16 15:53:23,901] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-01-16 15:53:23,910] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): check_file_if_exists> on 2024-01-16 15:53:22.144392+00:00
[2024-01-16 15:53:23,913] {standard_task_runner.py:52} INFO - Started process 1286 to run task
[2024-01-16 15:53:23,916] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_transfer_gdrive_to_postgresql', 'check_file_if_exists', 'manual__2024-01-16T15:53:22.144392+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/dag_gdrive_to_postgres.py', '--cfg-path', '/tmp/tmpe3r9bokf', '--error-file', '/tmp/tmprn7yhy2i']
[2024-01-16 15:53:23,917] {standard_task_runner.py:80} INFO - Job 37: Subtask check_file_if_exists
[2024-01-16 15:53:23,953] {task_command.py:369} INFO - Running <TaskInstance: dag_transfer_gdrive_to_postgresql.check_file_if_exists manual__2024-01-16T15:53:22.144392+00:00 [running]> on host 3c1ede9470c0
[2024-01-16 15:53:24,009] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_transfer_gdrive_to_postgresql
AIRFLOW_CTX_TASK_ID=check_file_if_exists
AIRFLOW_CTX_EXECUTION_DATE=2024-01-16T15:53:22.144392+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-16T15:53:22.144392+00:00
[2024-01-16 15:53:27,104] {logging_mixin.py:115} INFO - Successfully install google-api-python-client
[2024-01-16 15:53:30,104] {logging_mixin.py:115} INFO - Successfully install google-auth-httplib2
[2024-01-16 15:53:33,081] {logging_mixin.py:115} INFO - Successfully install google-auth
[2024-01-16 15:53:36,029] {logging_mixin.py:115} INFO - Successfully install google-auth-oauthlib
[2024-01-16 15:53:36,041] {logging_mixin.py:115} INFO - Credentials from token ya29.a0AfB_byCbo1LuaVau_lph7bh7WjmnYEa740lh58RaXUYRjPfEc1xAYOFdmhd5-NtKhAcgpYTZSoZkkFC2aMHWHib8LJIFRlD5WJBZYON-TITr2Jb3lZI01KfKnV6F7e_-MGDSNZB-V9cpFMW_YKpo6ZhvimsHofRl5Fl7OgaCgYKAaQSARMSFQHGX2MiNQbSQHbzKQLVfmHflPJQAw0173
[2024-01-16 15:53:36,041] {logging_mixin.py:115} INFO - <google.oauth2.credentials.Credentials object at 0xffff94516210>
[2024-01-16 15:53:37,213] {logging_mixin.py:115} INFO - The 'dataset' files does not exist in 'Shared with me' in folder 'dataset'.
[2024-01-16 15:53:37,214] {python.py:173} INFO - Done. Returned value was: end
[2024-01-16 15:53:37,241] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_transfer_gdrive_to_postgresql, task_id=check_file_if_exists, execution_date=20240116T155322, start_date=20240116T155323, end_date=20240116T155337
[2024-01-16 15:53:37,289] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-01-16 15:53:37,314] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
