[2024-01-16 15:55:44,768] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_transfer_gdrive_to_postgresql.check_file_if_exists manual__2024-01-16T15:55:42.602631+00:00 [queued]>
[2024-01-16 15:55:44,777] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_transfer_gdrive_to_postgresql.check_file_if_exists manual__2024-01-16T15:55:42.602631+00:00 [queued]>
[2024-01-16 15:55:44,777] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-01-16 15:55:44,778] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2024-01-16 15:55:44,778] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-01-16 15:55:44,789] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): check_file_if_exists> on 2024-01-16 15:55:42.602631+00:00
[2024-01-16 15:55:44,792] {standard_task_runner.py:52} INFO - Started process 1364 to run task
[2024-01-16 15:55:44,795] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_transfer_gdrive_to_postgresql', 'check_file_if_exists', 'manual__2024-01-16T15:55:42.602631+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/dag_gdrive_to_postgres.py', '--cfg-path', '/tmp/tmpsrzbcgyp', '--error-file', '/tmp/tmp0ae3k4_p']
[2024-01-16 15:55:44,796] {standard_task_runner.py:80} INFO - Job 41: Subtask check_file_if_exists
[2024-01-16 15:55:44,833] {task_command.py:369} INFO - Running <TaskInstance: dag_transfer_gdrive_to_postgresql.check_file_if_exists manual__2024-01-16T15:55:42.602631+00:00 [running]> on host 3c1ede9470c0
[2024-01-16 15:55:44,882] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_transfer_gdrive_to_postgresql
AIRFLOW_CTX_TASK_ID=check_file_if_exists
AIRFLOW_CTX_EXECUTION_DATE=2024-01-16T15:55:42.602631+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-16T15:55:42.602631+00:00
[2024-01-16 15:55:48,064] {logging_mixin.py:115} INFO - Successfully install google-api-python-client
[2024-01-16 15:55:51,117] {logging_mixin.py:115} INFO - Successfully install google-auth-httplib2
[2024-01-16 15:55:54,052] {logging_mixin.py:115} INFO - Successfully install google-auth
[2024-01-16 15:55:57,067] {logging_mixin.py:115} INFO - Successfully install google-auth-oauthlib
[2024-01-16 15:55:57,080] {logging_mixin.py:115} INFO - Credentials from token ya29.a0AfB_byCbo1LuaVau_lph7bh7WjmnYEa740lh58RaXUYRjPfEc1xAYOFdmhd5-NtKhAcgpYTZSoZkkFC2aMHWHib8LJIFRlD5WJBZYON-TITr2Jb3lZI01KfKnV6F7e_-MGDSNZB-V9cpFMW_YKpo6ZhvimsHofRl5Fl7OgaCgYKAaQSARMSFQHGX2MiNQbSQHbzKQLVfmHflPJQAw0173
[2024-01-16 15:55:57,080] {logging_mixin.py:115} INFO - <google.oauth2.credentials.Credentials object at 0xffff9451c090>
[2024-01-16 15:55:58,250] {logging_mixin.py:115} INFO - [{'id': '1rzPInbJFi86HYocPCcptsDflfIYvkzqF', 'name': 'dataset'}]
[2024-01-16 15:55:58,251] {logging_mixin.py:115} INFO - 3
[2024-01-16 15:55:58,251] {logging_mixin.py:115} INFO - The. 'dataset' folder exists in 'Shared with me'.
[2024-01-16 15:55:58,252] {logging_mixin.py:115} INFO - 4
[2024-01-16 15:55:58,666] {logging_mixin.py:115} INFO - 5
[2024-01-16 15:55:58,668] {logging_mixin.py:115} INFO - dataset_files: []
[2024-01-16 15:55:58,668] {logging_mixin.py:115} INFO - 7
[2024-01-16 15:55:58,668] {logging_mixin.py:115} INFO - No files found in 'dataset' folder.
[2024-01-16 15:55:58,669] {python.py:173} INFO - Done. Returned value was: end
[2024-01-16 15:55:58,715] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_transfer_gdrive_to_postgresql, task_id=check_file_if_exists, execution_date=20240116T155542, start_date=20240116T155544, end_date=20240116T155558
[2024-01-16 15:55:58,768] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-01-16 15:55:58,791] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
