[2024-01-16 16:08:31,078] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_transfer_gdrive_to_postgresql.process_csv manual__2024-01-16T16:03:13.118923+00:00 [queued]>
[2024-01-16 16:08:31,084] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_transfer_gdrive_to_postgresql.process_csv manual__2024-01-16T16:03:13.118923+00:00 [queued]>
[2024-01-16 16:08:31,084] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-01-16 16:08:31,085] {taskinstance.py:1357} INFO - Starting attempt 2 of 3
[2024-01-16 16:08:31,085] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-01-16 16:08:31,093] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): process_csv> on 2024-01-16 16:03:13.118923+00:00
[2024-01-16 16:08:31,096] {standard_task_runner.py:52} INFO - Started process 1692 to run task
[2024-01-16 16:08:31,100] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_transfer_gdrive_to_postgresql', 'process_csv', 'manual__2024-01-16T16:03:13.118923+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/dag_gdrive_to_postgres.py', '--cfg-path', '/tmp/tmplkojt6_k', '--error-file', '/tmp/tmpt8yo85k0']
[2024-01-16 16:08:31,101] {standard_task_runner.py:80} INFO - Job 50: Subtask process_csv
[2024-01-16 16:08:31,140] {task_command.py:369} INFO - Running <TaskInstance: dag_transfer_gdrive_to_postgresql.process_csv manual__2024-01-16T16:03:13.118923+00:00 [running]> on host 3c1ede9470c0
[2024-01-16 16:08:31,193] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_transfer_gdrive_to_postgresql
AIRFLOW_CTX_TASK_ID=process_csv
AIRFLOW_CTX_EXECUTION_DATE=2024-01-16T16:03:13.118923+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-16T16:03:13.118923+00:00
[2024-01-16 16:08:31,201] {logging_mixin.py:115} INFO - file:  2023-10-02.csv
[2024-01-16 16:08:31,201] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_gdrive_to_postgres.py", line 146, in _process_csv
    writer = csv.DictWriter(output_file, fieldnames=fieldnames)
  File "/usr/local/lib/python3.7/csv.py", line 140, in __init__
    self.writer = writer(f, dialect, *args, **kwds)
TypeError: argument 1 must have a "write" method
[2024-01-16 16:08:31,208] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_transfer_gdrive_to_postgresql, task_id=process_csv, execution_date=20240116T160313, start_date=20240116T160831, end_date=20240116T160831
[2024-01-16 16:08:31,214] {standard_task_runner.py:97} ERROR - Failed to execute job 50 for task process_csv (argument 1 must have a "write" method; 1692)
[2024-01-16 16:08:31,235] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-01-16 16:08:31,261] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
