[2024-01-16 15:20:32,948] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_transfer_gdrive_to_postgresql.check_file_if_exists manual__2024-01-16T15:20:31.819719+00:00 [queued]>
[2024-01-16 15:20:32,955] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_transfer_gdrive_to_postgresql.check_file_if_exists manual__2024-01-16T15:20:31.819719+00:00 [queued]>
[2024-01-16 15:20:32,955] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-01-16 15:20:32,956] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2024-01-16 15:20:32,956] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-01-16 15:20:32,965] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): check_file_if_exists> on 2024-01-16 15:20:31.819719+00:00
[2024-01-16 15:20:32,969] {standard_task_runner.py:52} INFO - Started process 408 to run task
[2024-01-16 15:20:32,971] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_transfer_gdrive_to_postgresql', 'check_file_if_exists', 'manual__2024-01-16T15:20:31.819719+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag_gdrive_to_postgres.py', '--cfg-path', '/tmp/tmpsl6qfbxw', '--error-file', '/tmp/tmpycszq0pf']
[2024-01-16 15:20:32,972] {standard_task_runner.py:80} INFO - Job 13: Subtask check_file_if_exists
[2024-01-16 15:20:33,009] {task_command.py:369} INFO - Running <TaskInstance: dag_transfer_gdrive_to_postgresql.check_file_if_exists manual__2024-01-16T15:20:31.819719+00:00 [running]> on host 3c1ede9470c0
[2024-01-16 15:20:33,057] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_transfer_gdrive_to_postgresql
AIRFLOW_CTX_TASK_ID=check_file_if_exists
AIRFLOW_CTX_EXECUTION_DATE=2024-01-16T15:20:31.819719+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-16T15:20:31.819719+00:00
[2024-01-16 15:20:33,058] {logging_mixin.py:115} INFO - 1
[2024-01-16 15:20:33,074] {logging_mixin.py:115} INFO - 2
[2024-01-16 15:20:33,076] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_gdrive_to_postgres.py", line 82, in _check_file_if_exist
    creds = __authenticate()
  File "/opt/airflow/dags/dag_gdrive_to_postgres.py", line 28, in __authenticate
    __install_packages(packages_to_install)
  File "/opt/airflow/dags/dag_gdrive_to_postgres.py", line 18, in __install_packages
    subprocess.check_call('pip3', 'install', package)
  File "/usr/local/lib/python3.7/subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.7/subprocess.py", line 702, in __init__
    raise TypeError("bufsize must be an integer")
TypeError: bufsize must be an integer
[2024-01-16 15:20:33,083] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_transfer_gdrive_to_postgresql, task_id=check_file_if_exists, execution_date=20240116T152031, start_date=20240116T152032, end_date=20240116T152033
[2024-01-16 15:20:33,090] {standard_task_runner.py:97} ERROR - Failed to execute job 13 for task check_file_if_exists (bufsize must be an integer; 408)
[2024-01-16 15:20:33,110] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-01-16 15:20:33,137] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
