[2024-01-14 12:41:31,360] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_transfer_gdrive_to_postgresql.check_file_if_exists manual__2024-01-14T11:47:04.375078+00:00 [queued]>
[2024-01-14 12:41:31,366] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_transfer_gdrive_to_postgresql.check_file_if_exists manual__2024-01-14T11:47:04.375078+00:00 [queued]>
[2024-01-14 12:41:31,367] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-01-14 12:41:31,367] {taskinstance.py:1357} INFO - Starting attempt 2 of 3
[2024-01-14 12:41:31,367] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-01-14 12:41:31,374] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): check_file_if_exists> on 2024-01-14 11:47:04.375078+00:00
[2024-01-14 12:41:31,378] {standard_task_runner.py:52} INFO - Started process 9111 to run task
[2024-01-14 12:41:31,380] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_transfer_gdrive_to_postgresql', 'check_file_if_exists', 'manual__2024-01-14T11:47:04.375078+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag_gdrive_to_postgres.py', '--cfg-path', '/tmp/tmpex_uqxps', '--error-file', '/tmp/tmptr2k8oag']
[2024-01-14 12:41:31,381] {standard_task_runner.py:80} INFO - Job 6: Subtask check_file_if_exists
[2024-01-14 12:41:31,410] {task_command.py:369} INFO - Running <TaskInstance: dag_transfer_gdrive_to_postgresql.check_file_if_exists manual__2024-01-14T11:47:04.375078+00:00 [running]> on host 3c1ede9470c0
[2024-01-14 12:41:31,450] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_transfer_gdrive_to_postgresql
AIRFLOW_CTX_TASK_ID=check_file_if_exists
AIRFLOW_CTX_EXECUTION_DATE=2024-01-14T11:47:04.375078+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-14T11:47:04.375078+00:00
[2024-01-14 12:41:31,466] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_gdrive_to_postgres.py", line 86, in _check_file_if_exist
    creds = __authenticate()
  File "/opt/airflow/dags/dag_gdrive_to_postgres.py", line 28, in __authenticate
    __install_packages(packages_to_install)
  File "/opt/airflow/dags/dag_gdrive_to_postgres.py", line 18, in __install_packages
    subprocess.check_call('pip3', 'install', package)
  File "/usr/local/lib/python3.7/subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.7/subprocess.py", line 702, in __init__
    raise TypeError("bufsize must be an integer")
TypeError: bufsize must be an integer
[2024-01-14 12:41:31,472] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_transfer_gdrive_to_postgresql, task_id=check_file_if_exists, execution_date=20240114T114704, start_date=20240114T124131, end_date=20240114T124131
[2024-01-14 12:41:31,477] {standard_task_runner.py:97} ERROR - Failed to execute job 6 for task check_file_if_exists (bufsize must be an integer; 9111)
[2024-01-14 12:41:31,516] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-01-14 12:41:31,539] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
