[2024-01-16 16:23:31,337] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_transfer_gdrive_to_postgresql.create_ddl manual__2024-01-16T16:23:13.309978+00:00 [queued]>
[2024-01-16 16:23:31,343] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_transfer_gdrive_to_postgresql.create_ddl manual__2024-01-16T16:23:13.309978+00:00 [queued]>
[2024-01-16 16:23:31,343] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-01-16 16:23:31,343] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2024-01-16 16:23:31,344] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-01-16 16:23:31,352] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_ddl> on 2024-01-16 16:23:13.309978+00:00
[2024-01-16 16:23:31,355] {standard_task_runner.py:52} INFO - Started process 2138 to run task
[2024-01-16 16:23:31,358] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_transfer_gdrive_to_postgresql', 'create_ddl', 'manual__2024-01-16T16:23:13.309978+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/dag_gdrive_to_postgres.py', '--cfg-path', '/tmp/tmp29ufr9wu', '--error-file', '/tmp/tmphpsrc6m0']
[2024-01-16 16:23:31,359] {standard_task_runner.py:80} INFO - Job 63: Subtask create_ddl
[2024-01-16 16:23:31,392] {task_command.py:369} INFO - Running <TaskInstance: dag_transfer_gdrive_to_postgresql.create_ddl manual__2024-01-16T16:23:13.309978+00:00 [running]> on host 3c1ede9470c0
[2024-01-16 16:23:31,437] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_transfer_gdrive_to_postgresql
AIRFLOW_CTX_TASK_ID=create_ddl
AIRFLOW_CTX_EXECUTION_DATE=2024-01-16T16:23:13.309978+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-16T16:23:13.309978+00:00
[2024-01-16 16:23:34,268] {logging_mixin.py:115} INFO - Successfully install psycopg2-binary
[2024-01-16 16:23:34,269] {logging_mixin.py:115} INFO - Connecting to the PostgreSOL database... os.environ.get ('POSTGRES_USER') ***
[2024-01-16 16:23:34,269] {logging_mixin.py:115} INFO - Error: could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5434?
[2024-01-16 16:23:34,270] {python.py:173} INFO - Done. Returned value was: could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5434?

[2024-01-16 16:23:34,276] {xcom.py:585} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2024-01-16 16:23:34,277] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2380, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 197, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 582, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type OperationalError is not JSON serializable
[2024-01-16 16:23:34,284] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_transfer_gdrive_to_postgresql, task_id=create_ddl, execution_date=20240116T162313, start_date=20240116T162331, end_date=20240116T162334
[2024-01-16 16:23:34,292] {standard_task_runner.py:97} ERROR - Failed to execute job 63 for task create_ddl (Object of type OperationalError is not JSON serializable; 2138)
[2024-01-16 16:23:34,315] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-01-16 16:23:34,341] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
