[2024-01-16 16:15:51,209] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_transfer_gdrive_to_postgresql.create_ddl manual__2024-01-16T16:10:29.097873+00:00 [queued]>
[2024-01-16 16:15:51,215] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_transfer_gdrive_to_postgresql.create_ddl manual__2024-01-16T16:10:29.097873+00:00 [queued]>
[2024-01-16 16:15:51,216] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-01-16 16:15:51,216] {taskinstance.py:1357} INFO - Starting attempt 2 of 3
[2024-01-16 16:15:51,216] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-01-16 16:15:51,225] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_ddl> on 2024-01-16 16:10:29.097873+00:00
[2024-01-16 16:15:51,228] {standard_task_runner.py:52} INFO - Started process 1880 to run task
[2024-01-16 16:15:51,231] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_transfer_gdrive_to_postgresql', 'create_ddl', 'manual__2024-01-16T16:10:29.097873+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/dag_gdrive_to_postgres.py', '--cfg-path', '/tmp/tmp37z_u9jj', '--error-file', '/tmp/tmpyxqx9e4l']
[2024-01-16 16:15:51,232] {standard_task_runner.py:80} INFO - Job 54: Subtask create_ddl
[2024-01-16 16:15:51,268] {task_command.py:369} INFO - Running <TaskInstance: dag_transfer_gdrive_to_postgresql.create_ddl manual__2024-01-16T16:10:29.097873+00:00 [running]> on host 3c1ede9470c0
[2024-01-16 16:15:51,316] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_transfer_gdrive_to_postgresql
AIRFLOW_CTX_TASK_ID=create_ddl
AIRFLOW_CTX_EXECUTION_DATE=2024-01-16T16:10:29.097873+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-16T16:10:29.097873+00:00
[2024-01-16 16:15:54,318] {logging_mixin.py:115} INFO - Successfully install psycopg2-binary
[2024-01-16 16:15:54,319] {logging_mixin.py:115} INFO - Connecting to the PostgreSOL database... os.environ.get ('POSTGRES_USER') ***
[2024-01-16 16:15:54,319] {logging_mixin.py:115} INFO - Error: 'module' object is not callable
[2024-01-16 16:15:54,319] {python.py:173} INFO - Done. Returned value was: 'module' object is not callable
[2024-01-16 16:15:54,328] {xcom.py:585} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2024-01-16 16:15:54,329] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2380, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 197, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 582, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type TypeError is not JSON serializable
[2024-01-16 16:15:54,338] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_transfer_gdrive_to_postgresql, task_id=create_ddl, execution_date=20240116T161029, start_date=20240116T161551, end_date=20240116T161554
[2024-01-16 16:15:54,347] {standard_task_runner.py:97} ERROR - Failed to execute job 54 for task create_ddl (Object of type TypeError is not JSON serializable; 1880)
[2024-01-16 16:15:54,366] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-01-16 16:15:54,397] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
